### ISSUE TITLE
I made a ESP8266 fork which include OTA updates

### ISSUE THREAD

**Issue by Skaronator** [newAM/LoadCellOccupany#2]
Thanks @newAM for publishing your work. I wouldn't be able to do this project otherwise. Especially the 3D printed case.

___

In case someone build it's own version with a ESP8266 you might be interested in my fork. It connects via WiFi (obv) and support Over The Air updates.

It also saves the 'tare'/offset to the EEPROM and doesn't reset on restart/power off. And it only sends MQTT updates if the load has changed. (reduce the load on MQTT broker)

https://github.com/Skaronator/ESP8266-Load-Cell

**Comment by newAM** [comment]
Thanks for the kind words!  I added your project in the md of mine so people can find it.  I also incorporated the broker load reduction, great idea!
