### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by ikrowni** [newAM/LoadCellOccupany#5]
The image of the final product looks different from the boards you mention as the hardware. I would like to have the input jacks and PoE but where do i purchase that specific board?

If my bed has 6 legs will that interfere? I have a purple mattress and it is very very heavy so there are 6 large cylinders for the legs. Can i use 6 load cell sensors just to have it all balanced properly?

**Comment by newAM** [comment]
I'm not sure I understand, what is different from my image of the final product?  These boards cannot be purchased fully assembled, I had the PCB fabricated at OSH park and purchased the components on Digikey then soldered it together by hand.

6 legs should be ok, you can modify the design to utilize more load cells if you wish, the HX711 does have another different input that I did not utilize.  It would probably work well enough if you just put spacers under the two extra legs as well.  You mention your bed is heavy though, it is a good idea to double check that the occupants mass + the mass of your bed will not exceed the load cells limit.
