### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by gth758y** [newAM/LoadCellOccupany#6]
I'm running into an issue on line 34 when I try to compile the code.

```
exit status 1
no matching function to call to 'HX711::HX711(int, int)'
```
I'm using bodge's library here: https://github.com/bogde/HX711

Is there a different library I should be using instead? 

As an aside, thanks for publishing this project. I've been hoping to do something similar for quite a while and I've learned a ton of new things by working on it.

**Comment by newAM** [comment]
I think they did a bit of refactoring to that library since I used it.  This is the commit I used for this project: https://github.com/bogde/HX711/commit/e80de1c07e990e07627ec215eec9e1efabf281ee

Does that one work for you?

**Comment by gth758y** [comment]
Bingo! That did it. Thanks for the quick response!

**Comment by newAM** [comment]
Woo!  Glad it works!  I added the commit hash in the README, thanks for finding the bug!
