### ISSUE TITLE
W5500 vs W5100

### ISSUE THREAD

**Issue by gth758y** [newAM/LoadCellOccupany#9]
Just curious if you saw any technical reason that the Wiznet W5500 chip couldn't be used instead of the W5100 for this application. I'm thinking the 48-LQFP package of the W5500 would be significantly easier to solder than the 80-LQFP of the W5100. I'd have to redesign the board, but that may also reduce the number of caps needed as well.

[W5500 on Digikey](https://www.digikey.com/product-detail/en/wiznet/W5500/1278-1021-ND/4425702)

Looking over the datasheets, it looks to me like there are pins on the W5500 that closely match the pins being used on the W5100, but admittedly this isn't my area of expertise. Thoughts?

**Comment by newAM** [comment]
There's no good reason for the decision, other than that the W5100 was what I had on hand when I was prototyping.  I have used the W5500 in my later designs (see: https://github.com/newAM/AmbientSensor) and I much prefer it.

The W5500 has a different PHY, and a slightly different programmers interface (there is an Arduino library though).  Apart from that it should be relatively drop-in.

**Comment by gth758y** [comment]
Great, I'll look into implementing it for this. Thanks a bunch!
